# Generated by Django 4.2.25 on 2025-11-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('vaccinated', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
