# Generated by Django 4.2.25 on 2025-11-27 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(default='pending', max_length=20)),
                ('Amount', models.IntegerField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('shop_photo', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Details', models.CharField(max_length=300)),
                ('Photo', models.FileField(upload_to='')),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Order_table_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Status', models.CharField(default='pending', max_length=20)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_table_main')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_table')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Total_amount', models.BigIntegerField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
