# Generated by Django 4.2.25 on 2025-11-27 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_order_table_main_shop_product_table_order_table_sub_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Shop_signup_table',
        ),
    ]
