# Generated by Django 4.2.25 on 2025-12-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_signup_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.shop_signup_table'),
            preserve_default=False,
        ),
    ]
