# Generated by Django 4.2.25 on 2025-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pet_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
